# Generated by Django 2.0.2 on 2018-05-02 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Login')),
                ('senha', models.CharField(max_length=50, verbose_name='Senha')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('dt_expiracao', models.DateField(max_length=10, verbose_name='Data Expiracao')),
                ('ra', models.CharField(max_length=7, verbose_name='RA')),
                ('foto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Login')),
                ('senha', models.CharField(max_length=50, verbose_name='Senha')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('dt_expiracao', models.DateField(max_length=10, verbose_name='Data Expiracao')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('Data', models.DateField(verbose_name='Data')),
                ('Status', models.CharField(max_length=255, verbose_name='Status')),
                ('PlanoDeEnsino', models.CharField(max_length=255, verbose_name='PlanoDeEnsino')),
                ('CargaHoraria', models.SmallIntegerField(verbose_name='CargaHoraria')),
                ('Competencias', models.CharField(max_length=255, verbose_name='Competencias')),
                ('Habilidades', models.CharField(max_length=255, verbose_name='Habilidades')),
                ('Ementa', models.CharField(max_length=255, verbose_name='Ementa')),
                ('ConteudoProgramatico', models.CharField(max_length=255, verbose_name='ConteudoProgramatico')),
                ('BibliografiaBasica', models.CharField(max_length=255, verbose_name='BibliografiaBasica')),
                ('BibliografiaComplementar', models.CharField(max_length=255, verbose_name='BibliografiaComplementar')),
                ('PercentualPratico', models.SmallIntegerField(verbose_name='PercentualPratico')),
                ('PercentualTeorico', models.SmallIntegerField(verbose_name='PercentualTeorico')),
                ('IdCoordenador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Coordenador')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('DtInicioMatricula', models.DateField(null=True, verbose_name='DtInicioMatricula')),
                ('DtFimMatricula', models.DateField(null=True, verbose_name='DtFimMatricula')),
                ('Ano', models.SmallIntegerField(verbose_name='Ano')),
                ('Semestre', models.SmallIntegerField(verbose_name='Semestre')),
                ('Turma', models.CharField(max_length=255, verbose_name='Turma')),
                ('Metodologia', models.CharField(max_length=255, null=True, verbose_name='Metodologia')),
                ('Recursos', models.CharField(max_length=255, null=True, verbose_name='Recursos')),
                ('CriterioAvaliacao', models.CharField(max_length=255, null=True, verbose_name='CriterioAvaliacao')),
                ('PlanoDeAulas', models.CharField(max_length=255, null=True, verbose_name='PlanoDeAulas')),
                ('IdCoordenador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Coordenador')),
                ('IdCurso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Curso')),
                ('IdDisciplina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('referencia', models.CharField(max_length=255, verbose_name='Referencia')),
                ('conteudo', models.CharField(max_length=255, verbose_name='Conteudo')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('dtEnvio', models.DateTimeField(max_length=10, verbose_name='Data Envio')),
                ('dtResposta', models.DateField(max_length=10, verbose_name='Data Resposta')),
                ('resposta', models.CharField(max_length=255, verbose_name='Resposta')),
                ('Alunos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.Alunos')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Login')),
                ('senha', models.CharField(max_length=50, verbose_name='Senha')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('dt_expiracao', models.DateField(max_length=10, verbose_name='Data Expiracao')),
                ('apelido', models.CharField(max_length=25, verbose_name='Apelido')),
            ],
        ),
        migrations.AddField(
            model_name='mensagem',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.Professor'),
        ),
        migrations.AddField(
            model_name='disciplinaofertada',
            name='IdProfessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Professor'),
        ),
    ]
