# Generated by Django 2.0.2 on 2018-05-02 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0003_mensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('decricao', models.CharField(max_length=255, verbose_name='Descricao')),
                ('conteudo', models.CharField(max_length=255, verbose_name='Conteudo')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
                ('extras', models.CharField(max_length=255, verbose_name='Extras')),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.Professor')),
            ],
        ),
    ]
