# Generated by Django 2.0.2 on 2018-05-02 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0004_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeVinculada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=255, verbose_name='Rotulo')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('DtInicioRespostas', models.DateField(max_length=10, verbose_name='DtInicioRespostas')),
                ('DtFimRespostas', models.DateField(max_length=10, verbose_name=' DtFimRespostas')),
                ('Atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.Atividade')),
                ('DisciplinaOfertada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.DisciplinaOfertada')),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.Professor')),
            ],
        ),
    ]
