# Generated by Django 2.0.2 on 2018-05-02 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0005_atividadevinculada'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DtSolicitacao', models.DateField(verbose_name='DataSolicitacao')),
                ('Status', models.CharField(max_length=255, verbose_name='Status')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.Alunos')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.Coordenador')),
                ('disciplinaOfertada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.DisciplinaOfertada')),
            ],
        ),
    ]
