# Generated by Django 2.0.2 on 2018-05-02 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0006_solicitacaomatricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('resposta', models.CharField(max_length=50, verbose_name='Resposta')),
                ('DtEntrega', models.DateField(max_length=10, verbose_name='DtEntrega')),
                ('Status', models.CharField(max_length=50, verbose_name='Status')),
                ('Nota', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota')),
                ('DtAvaliacao', models.DateField(max_length=10, verbose_name='DtAvaliacao')),
                ('Obs', models.CharField(max_length=50, verbose_name='Obs')),
                ('Aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.Alunos')),
                ('AtividadeVinculada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.AtividadeVinculada')),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.Professor')),
            ],
        ),
    ]
